### PR TITLE
Ethane example using charmm-gui, mbuild, gmx, mdtraj

### PR DESCRIPTION
**Pull request by ahy3nz**
#5

### CODE REVIEW

**Comment by ahy3nz** [comment]
I might have gone a little trigger-happy with `jupyter nbconvert` but otherwise I think this is done. The goal is to show how users can pre-parametrize molecules with charmm-gui and still use mbuild

**Comment by rmatsum836** [comment]
I think this example is ready to go as well.

**Comment by uppittu11** [comment]
Also, did you get the reference data from a previous simulation? Can you stick the experimental density in there instead?

**Comment by mattwthompson** [comment]
Worked for me out of the box. I agree with the points Parashara brought up, but all I did was add a note if a user wanted to run for longer. I'm still not sure how to generally deal with simulation length in these workflow examples.

**Pull request merged**
