### PR TITLE
Gomc-propane

### PR DESCRIPTION
**Pull request by ahy3nz**
This workflow shows how to use mbuild + foyer to construct a simple box of ethane for a GOMC NVT simulation. Largely ParmEd can handle most of the file writing. There's some post-processing that needs to be done to the PAR file, but it's pretty trivial within the notebook. There's also an additional module to put together a rudimentary simulation input/control file.

This is still a work in progress (still need to get to the analysis bit), but I welcome other input/opinions

### CODE REVIEW

**Comment by mattwthompson** [comment]
Thanks for starting in on this! Two questions I have right off the bat:

1. Is there any way to install GOMC without building from source?
2. The system appears to be a 3:1 propane bead, but the force field loaded in is GAFF?

**Comment by ahy3nz** [comment]
It was somewhat straightforward following instructions on the [readme](https://github.com/GOMC-WSU/GOMC/)

I took the atomistic propane from the mbuild examples, but it looks like its formula is CH2 CH2 CH3 (there's too many CH2 moieities...)

I picked GAFF because the lengths of the atomtypes are short. If we wanted to use OPLS, we'd need to map the atomtypes to shortened versions that will fit the CHARMM PAR file spec. This is doable, so if using OPLS is preferred, I can refactor

**Comment by mattwthompson** [comment]
It looks like that class is from inside the CG hexane example, so it's an "uncapped" propane.

https://github.com/mosdef-hub/mbuild/blob/b36cff8c6b93616e069fba1a877099b70909053e/mbuild/examples/__init__.py#L7

https://github.com/mosdef-hub/mbuild/blob/b36cff8c6b93616e069fba1a877099b70909053e/mbuild/examples/coarse_graining/cg_hexane.py#L14-15

That being said, propane seems like a good molecule, maybe `mb.load('CCC', smiles=True)` would be better?

GAFF seems like an appropriate choice, I misread the cell and thought you just make a new compound and called it propane (which would be all that's needed to make a 3:1 propane bead).

And those installation instructions look reasonable enough for GOMC; I think for the purposes of this example it's fair to assume the user has successfully installed it.

**Comment by ahy3nz** [comment]
Switched back to ethane. Thanks to our GOMC friends, this simulation runs successfully. I will scrape together some primitive analysis

**Comment by ahy3nz** [comment]
Okay looking for eyes on this now. This goes from building in mbuild+foyer, simulating in gomc, doing some basic analysis with numpy+pandas+matplotlib

**Comment by ahy3nz** [comment]
This PR has 2 mosdef-gomc workflows now: NVT and GEMC. They are both complete for build + simulate + analyze

Looking for comments/opinions. Most of the PDB, DAT, PAR, and PSF files can be removed if desired (they get generated from the notebooks)

**Pull request merged**
